import { Dealer } from "@/types/dealer";

export const dealers: Dealer[] = [
  {
    id: "1",
    dealer_name: "Gentech Guard Mumbai Central",
    contact_person: "Rajesh Sharma",
    phone: "+91 99898 20222",
    email: "mumbai@gentechguard.com",
    address: "123 Marine Drive, Near Oberoi Mall",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400002",
    map_position_x: 28.5,
    map_position_y: 65.2,
    is_active: true,
    dealer_type: "premium",
    created_at: "2024-01-15"
  },
  {
    id: "2",
    dealer_name: "Delhi Premium Auto Care",
    contact_person: "Vikram Singh",
    phone: "+91 99898 20223",
    email: "delhi@gentechguard.com",
    address: "456 Connaught Place, New Delhi",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
    map_position_x: 42.8,
    map_position_y: 32.5,
    is_active: true,
    dealer_type: "premium",
    created_at: "2024-01-20"
  },
  {
    id: "3",
    dealer_name: "Bangalore South PPF Center",
    contact_person: "Priya Kumar",
    phone: "+91 99898 20224",
    email: "bangalore@gentechguard.com",
    address: "789 Koramangala, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560034",
    map_position_x: 32.1,
    map_position_y: 78.4,
    is_active: true,
    dealer_type: "premium",
    created_at: "2024-02-01"
  },
  {
    id: "4",
    dealer_name: "Hyderabad Auto Shield",
    contact_person: "Suresh Reddy",
    phone: "+91 99898 20225",
    email: "hyderabad@gentechguard.com",
    address: "321 Banjara Hills, Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500034",
    map_position_x: 38.5,
    map_position_y: 68.3,
    is_active: true,
    dealer_type: "premium",
    created_at: "2024-02-10"
  },
  {
    id: "5",
    dealer_name: "Chennai Coastal Protection",
    contact_person: "Karthik Venkat",
    phone: "+91 99898 20226",
    email: "chennai@gentechguard.com",
    address: "654 Anna Salai, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600002",
    map_position_x: 35.2,
    map_position_y: 85.6,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-02-15"
  },
  {
    id: "6",
    dealer_name: "Kolkata East Auto Films",
    contact_person: "Arjun Banerjee",
    phone: "+91 99898 20227",
    email: "kolkata@gentechguard.com",
    address: "987 Park Street, Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700016",
    map_position_x: 62.5,
    map_position_y: 48.3,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-02-20"
  },
  {
    id: "7",
    dealer_name: "Pune West Auto Care",
    contact_person: "Amit Patil",
    phone: "+91 99898 20228",
    email: "pune@gentechguard.com",
    address: "147 FC Road, Pune",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411004",
    map_position_x: 30.2,
    map_position_y: 62.8,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-01"
  },
  {
    id: "8",
    dealer_name: "Ahmedabad Gujarat Auto Shield",
    contact_person: "Naresh Patel",
    phone: "+91 99898 20229",
    email: "ahmedabad@gentechguard.com",
    address: "258 CG Road, Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380009",
    map_position_x: 22.5,
    map_position_y: 48.6,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-05"
  },
  {
    id: "9",
    dealer_name: "Jaipur Royal Auto Protection",
    contact_person: "Rajendra Singh",
    phone: "+91 99898 20230",
    email: "jaipur@gentechguard.com",
    address: "369 MI Road, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302001",
    map_position_x: 35.8,
    map_position_y: 38.2,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-10"
  },
  {
    id: "10",
    dealer_name: "Kochi Kerala Auto Films",
    contact_person: "Thomas George",
    phone: "+91 99898 20231",
    email: "kochi@gentechguard.com",
    address: "741 MG Road, Kochi",
    city: "Kochi",
    state: "Kerala",
    pincode: "682011",
    map_position_x: 30.5,
    map_position_y: 88.2,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-15"
  },
  {
    id: "11",
    dealer_name: "Chandigarh North Auto Care",
    contact_person: "Harpreet Singh",
    phone: "+91 99898 20232",
    email: "chandigarh@gentechguard.com",
    address: "852 Sector 17, Chandigarh",
    city: "Chandigarh",
    state: "Chandigarh",
    pincode: "160017",
    map_position_x: 40.2,
    map_position_y: 28.5,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-20"
  },
  {
    id: "12",
    dealer_name: "Lucknow UP Auto Shield",
    contact_person: "Amitabh Tiwari",
    phone: "+91 99898 20233",
    email: "lucknow@gentechguard.com",
    address: "963 Hazratganj, Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226001",
    map_position_x: 45.5,
    map_position_y: 38.8,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-25"
  },
  {
    id: "13",
    dealer_name: "Bhopal MP Protection Center",
    contact_person: "Rahul Verma",
    phone: "+91 99898 20234",
    email: "bhopal@gentechguard.com",
    address: "159 MP Nagar, Bhopal",
    city: "Bhopal",
    state: "Madhya Pradesh",
    pincode: "462011",
    map_position_x: 38.8,
    map_position_y: 52.5,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-04-01"
  },
  {
    id: "14",
    dealer_name: "Visakhapatnam AP Films",
    contact_person: "Srinivas Rao",
    phone: "+91 99898 20235",
    email: "vizag@gentechguard.com",
    address: "357 Beach Road, Visakhapatnam",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    pincode: "530002",
    map_position_x: 48.5,
    map_position_y: 62.5,
    is_active: true,
    dealer_type: "coming_soon",
    created_at: "2024-04-05"
  },
  {
    id: "15",
    dealer_name: "Indore Premium Auto Care",
    contact_person: "Neeraj Gupta",
    phone: "+91 99898 20236",
    email: "indore@gentechguard.com",
    address: "753 MG Road, Indore",
    city: "Indore",
    state: "Madhya Pradesh",
    pincode: "452001",
    map_position_x: 36.5,
    map_position_y: 50.2,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-04-10"
  }
];

export const states = [
  "All States",
  "Andhra Pradesh",
  "Chandigarh",
  "Delhi",
  "Gujarat",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Rajasthan",
  "Tamil Nadu",
  "Telangana",
  "Uttar Pradesh",
  "West Bengal"
];

export const getDealerStats = () => {
  const activeDealers = dealers.filter(d => d.is_active);
  return {
    total: activeDealers.length,
    premium: activeDealers.filter(d => d.dealer_type === 'premium').length,
    standard: activeDealers.filter(d => d.dealer_type === 'standard').length,
    comingSoon: activeDealers.filter(d => d.dealer_type === 'coming_soon').length,
    cities: new Set(activeDealers.map(d => d.city)).size,
    states: new Set(activeDealers.map(d => d.state)).size
  };
};
